### ISSUE TITLE
[Diagrams]: Sequence Diagrams - First Version

### ISSUE THREAD

**Issue by aoengin** [bounswe/bounswe2024group6#281]
## Issue Description
For the sequence diagrams, we need to show how different parts of the system communicate with each other step by step. The goal is to map out the order of actions or messages exchanged for specific use cases, giving a clear picture of how the process works from start to finish.

## Tasks
- [x] List all sequence diagrams.
- [x] Create sequence diagrams.

## Estimated Time
Estimated Time: 4-5 hours

## Deadline
Deadline: 14/10/2024 - 12:59

## Reviewer Assignment
**Reviewer:** @YavizGuldalf 
Review Deadline: 14/10/2024 - 23:59

**Comment by aoengin** [comment]
I've created a tentative [list](https://github.com/bounswe/bounswe2024group6/wiki/CMPE-451-%E2%80%90-Sequence-Diagrams) for sequence diagrams.

**Comment by YavizGuldalf** [comment]
The list looks good to me, good job. We still need to discuss further in the lab and decide on the nature of the feed though.

**Comment by kaanyolcu22** [comment]
@YavizGuldalf can you check the [version](https://github.com/bounswe/bounswe2024group6/wiki/CMPE-451-%E2%80%90-Sequence-Diagrams) of the diagrams expect for Search Post and Search Quiz which will be implemented after the clear decision of searching functionality that we will take.

**Comment by YavizGuldalf** [comment]
I will take a look into that in around 2-3 hours, but what do you mean 'after the clear decision of searching functionality'? If you are talking about whether forum and quiz search will be mixed or separate we agreed on mixed in the last meeting. Or is it something related to the backend?

**Comment by kaanyolcu22** [comment]
No, it is about the semantic search functionality that we have not decided yet such as using wordnet or lexvo and also what results we will show after browsing a word.

**Comment by YavizGuldalf** [comment]
Here is my detailed review of the sequence diagrams thus far:

1. Feed::QuizFeed: I don't think there needs to be an alt between `no quizzes found` and` quizzes found`. Also, fetching only quizzes of the user's own level seems a little too constrictive. I think we should be allowing the Quiz Feed Service to pick the quizzes for a user depending on a number of factors including the results of the quizzes the person has taken recently, the people that they follow, their current level etc. For example, if a person of A2 level has done perfectly the last 10 A2 quizzes he has taken, there is little reason to not show this person quizzes of the B1 level. So I think it's best to complement the FetchQuizzesByLevel with a few more calls to the DB, such as FetchUsersFollowedUsers and FetchUserRecentQuizResults.
2. Post::Create Post: The term 'Thread' has been replaced by post, so CreatePost function found in the beginning should use the term 'Post' instead.
3. Post::Delete Post: Are we going to let users delete their own posts? The current use-case diagram and requirements do not allow this as there may be comments left by other people under that post. Also, all instances of 'thread' should be changed with 'post'.
4. Post::Upvote/Downvote Post: I think we agreed to change this to just like/unlike, so you can change the terminology around that (like instead of vote, etc). Also, the word 'thread' should be replaced by 'post'. 
5. Comment::Create Comment: I think comments don't need to have a title, but they do need to have a post under which they are commented. This information is missing in the `createComment` function. 
6. Comment::Upvote/Downvote Comment: I think we agreed to change this to just like/unlike, so you can change the terminology around that (like instead of vote, etc).
7. Quizzes::Create Quiz: I think we need another box for creating a loop for each question in the quiz in this sequence diagram. `fetchAnswerOptions` and `addQuestionToQuiz` functions should be inside of this loop. The loop can continue until the user finishes adding questions. 
8. Quizzes::Solve Quiz: We never really talked about 'passing' or 'failing' a quiz, I think it's best to leave it out of the sequence diagrams for now. Just saving the quiz results is enough I reckon. We can add it later if we all agree on that functionality.
9. Quizzes:: Add a Quiz to the Favourites: We do not call this functionality 'favouriting' in our app, we call it 'bookmarking', so all instances of 'favourite' should be changed with 'bookmark'. Also, I think this is a duplicate sequence diagram, there is also one called 'Bookmark Quiz'
10. Quizzes:: Remove a Quiz from the Favourites: We do not call this functionality 'favouriting' in our app, we call it 'bookmarking', so all instances of 'favourite' should be changed with 'bookmark'.

Other than these, the sequence diagrams look great guys, good job! While creating the sequence diagrams for search functionality, keep in mind that we agreed to have a single search for the whole app that will return both quizzes and forum posts (maybe even comments though that is up for debate, we haven't discussed that yet).

**Comment by aoengin** [comment]
@YavizGuldalf  I've made all the requested changes. Please let me know if I missed anything. Here is the [updated version](https://github.com/bounswe/bounswe2024group6/wiki/CMPE-451-%E2%80%90-Sequence-Diagrams/150b3b4a6410f871c2cd8a0b96c58cf662e98b4e).

**Comment by YavizGuldalf** [comment]
Okay, everything looks fine, but I think there is a mistake in the Delete Post sequence diagram. The Admin isn't connected to anywhere and there is still a 'User' and check post ownership functions.

**Comment by aoengin** [comment]
Please see the fixed [latest version](https://github.com/bounswe/bounswe2024group6/wiki/CMPE-451-%E2%80%90-Sequence-Diagrams/67b574526604ab4051f7541c8b699c897b0c6a6d).

**Comment by aoengin** [comment]
I didn't add this check initially because the actor was already an admin. However, I've decided to change the actor to a regular user and include a verification step.

I've updated in accordance with your requirements. Please see the [updated version](https://github.com/bounswe/bounswe2024group6/wiki/CMPE-451-%E2%80%90-Sequence-Diagrams/ab9446b4e5dac2ba9ec430f3d1d6945cadde2631).

**Comment by YavizGuldalf** [comment]
Looks good, thank you. We can now close this issue once the sequence diagrams for "searching" are complete.

**Comment by YavizGuldalf** [comment]
I have checked the sequence diagram for the search functionality, looks well thought-out, good job. I am now closing this issue.
